config/routes.rb
Rails.application.routes.draw do
  root to: "services#index"
  resources :services
  devise_for :users
  get "walker/dashboard", to: "walker#dashboard"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :services, dependent: :destroy
end

app/models/walker.rb
class Walker < ApplicationRecord
  validates :walker_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:is_walker])
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :find_service, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @service.user_id = current_user.id

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def authorize_user!
      return true if @service.user.id == current_user.id
      return false
      flash[:notice] = "You are not permitted to alter this service."
      redirect_to "/"
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:title, :description, :picture)
    end

    def find_service
      @service = Service.find(params[:id])
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
    Welcome <%= current_user.email %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign Up", new_user_registration_path %> or
    <%= link_to "Sign In", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Woofwalks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render "layouts/navbar" %>
      <p id="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true, class: "form") do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :picture %> <%= form.file_field :picture, accept:
  'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Your Walk</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Woof Walks</h1>

<div class='row'>
  <% @services.each do |service| %>
  <div class="card border-primary mb-3" style="max-width: 20rem; margin: 30px;">
  <div class="card-header">
    <%= link_to service do %>
      <%= image_tag service.picture if service.picture.attached? %>
    <% end %>
  </div>
  <div class="card-body">
    <h4 class="card-title"><%= service.title %></h4>
    <p class="card-text"><%= service.description %></p>
      <% if user_signed_in? && service.user_id == current_user.try(:id) %>
      <%= link_to 'Edit', edit_service_path(service) %>
      <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
  </div>
</div>
<% end %>
</div>

<br>

<% if user_signed_in? && current_user.is_walker == true %>
<%= link_to 'New Service', new_service_path %>
<% end %>

app/views/services/new.html.erb
<h1>New Walk</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
  <strong>Title:</strong>
  <%= @service.title %>
  </p>

  <p>
  <strong>Description:</strong>
  <%= @service.description %>
  </p>

  <p class="preview">
  <%= image_tag @service.picture if @service.picture.attached? %>
  </p>
</div>

<% if @service.user_id == current_user.id %>
  <%= link_to 'Edit', edit_service_path(@service) %> |
<% end %>

  <%= link_to 'Back', services_path %>